apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: codex-home
  name: codex-home
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
