apiVersion: ENC[AES256_GCM,data:JUQ=,iv:ve7ayIJZC0Us8DW3Nq7AjyH4l5bTFjja/PG/t+Q8uWw=,tag:rvskXrFzDZlplzBDSwhi3w==,type:str]
kind: ENC[AES256_GCM,data:gMih3O+U,iv:2NSyjT/dumx1fPmXGVWjn+a9me2bMKIjl3UKyR6Pxx4=,tag:nQV1UScj9M3ZOfe56xxSwQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:le2D9xBg92F1bQFmc3c=,iv:SHO7YEbWKBU8qch9rkKT6yBrAc04x2afvh7ut4fP0tQ=,tag:TG7Jrlvu9R3SYq95ryW6FA==,type:str]
    namespace: ENC[AES256_GCM,data:KIKXIA==,iv:y/QtKWNPeLwTWe0cMaysjIamoN0cCJKZSvLvJZKfS10=,tag:vpQmPG72+Ijlh/mpMNUuTg==,type:str]
stringData:
    ADZUNA_APP_ID: ""
    ADZUNA_APP_KEY: ""
    APIFY_TOKEN: ""
    BASIC_AUTH_PASSWORD: ""
    BASIC_AUTH_USER: ""
    GMAIL_OAUTH_CLIENT_ID: ""
    GMAIL_OAUTH_CLIENT_SECRET: ""
    RXRESUME_API_KEY: ""
    UKVISAJOBS_EMAIL: ""
    UKVISAJOBS_PASSWORD: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dte6kqnx7ny2khum85yed0l50xgra99l3j7z0z79zs89jsxh6u4qzygfrf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSXNjd2N5TFBuOVByL0Q1
            N3EyZTczN0VOU01VZVd3a1J1MnJ0UnBBN1VJCmhScWdkSUxFWlpCR05KV1FHRUhp
            Znl2Q1ozcmtkQ1V0UzZsc0pYYSsra28KLS0tIDFzOHV0SmRLbFVXbzVFek10c1U3
            ek56YUVlTmpqZXVBMllSbDU2cUxraW8KdZX0UBphYawY3TDaGaKkdtd5C2pP/bzI
            Y99cOtnxevYL593gOBGLxysciSgJLgcWI8gmn0Fuc9msxnsCXFlLKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T22:58:45Z"
    mac: ENC[AES256_GCM,data:zHUNnpV8mWXzD19SpPFojciv3RYp7oYKkdR9r7ssmGiMHUy1v3DMcw83APCk8qEUUpUs3W/8JavFweD9RzCCUVy/oZR7TU5mMCQva7Xxq0leI9Y/YBHB5o0F4UcXmASmoNp8Msn++o8H8Rq6dVPJCL0EEHqgE2wXiaOLPX6j5es=,iv:biWYDFZ3C5waipEqd0P85rmWsbUe2LBKQCMgWojVmmw=,tag:3jJHC6bizMZyTvYjtmwT9A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
