apiVersion: ENC[AES256_GCM,data:dBI=,iv:ue8H20EKrCQcbr+5vQrJysuK8SWdasXPyguTe9UsedA=,tag:s6iFUeFt+E2/Apaj/iSNNg==,type:str]
kind: ENC[AES256_GCM,data:qS/CSgq2,iv:2S53A2itLxWKd3iqrTVxSXp9ouwwS/PTZH9aqbFeoVc=,tag:PGEUxkVMW2p5NYKtD2SVTg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qn+vmv17SWzHqQvSSYPQL+NAXw==,iv:AYhav1smHDuLNGDiUiJt7M+b3StcbMoZNktQMIk4zsY=,tag:i77VJ5FdL/rJbEr2uKOGRg==,type:str]
    namespace: ENC[AES256_GCM,data:eSa80ts=,iv:XZ/2IgAJKuL0MEZkW9Rdygw1zMl7MkI/LqZPSbk1fSI=,tag:mwVjrPn4RrPgqvxxAfIR9Q==,type:str]
stringData:
    CB_ADMIN_NAME: ENC[AES256_GCM,data:xIITXl5qAVz7,iv:gGZUTdpRXuri0AMgPeZOH+3Jec2Nbm22Io1XOS4i4Tw=,tag:EbB5/Uht3vE0oNdAuXXkuQ==,type:str]
    CB_ADMIN_PASSWORD: ENC[AES256_GCM,data:/eb7MkK252886A==,iv:I4rJJrzQzoLLB0l8jVV/OIHESh8a2jn+7ZzurQdzreQ=,tag:Y/qXny5jV+qqd5uEsM1emQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dte6kqnx7ny2khum85yed0l50xgra99l3j7z0z79zs89jsxh6u4qzygfrf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWWpWR2tpWW5ML1BsQlU4
            U0plMXJFelBYVWRkVzh3TVI5NmQyMFBXV1RRCjJ2NW4xQkN4MEp0VXJzRmhSeVlZ
            cERKQVMyWGxKTGR3aVpGOXRLQ3dwTDQKLS0tIGlVWVZqaDg1bTc1dEJzSFBFMWY3
            NmZWc295bzVqa3k5MVhlaGVYbFpUaEkK1bnPymr/1xtdSECGeGf7WfcmS0OkNKRW
            OXqYnJiTKfcoOk/+M4Qfsign+SdQX/ZOJgH42+rftQ87KZpIxfF1oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T19:22:21Z"
    mac: ENC[AES256_GCM,data:mtQikJ0Fj0szKUMQV6xXn51nh+hAY2APBwgmxjtTiRfSxZf4elGBuRwEi8ZCFngCm/+hPC4Qg65xOk/Ozp0odbmhaDkeWofRMN3ha1PU9dkM8qiMCNN4eAjSTcJQ8tr7iJIeCj914yKfHfcW1Yzsfhxa8E/7ZW2YUm9wCmt/7rM=,iv:HbHra81XhU0+edltZJbB2LRwDXDsYlZg1FP0vRHivro=,tag:vMLlKLIadQrAWW5VSpWpIQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
