apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.5.18
    path: /mnt/ConderNAS/Plex/Downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-pvc
  namespace: tools
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: downloads-pv
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.5.18
    path: /mnt/ConderNAS/Plex/Movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies-pvc
  namespace: tools
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: movies-pv
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.5.18
    path: /mnt/ConderNAS/Plex/TV Shows
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv-pvc
  namespace: tools
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: tv-pv
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobooks-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.5.18
    path: /mnt/ConderNAS/Plex/Audiobooks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks-pvc
  namespace: tools
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: audiobooks-pv
  resources:
    requests:
      storage: 500Gi