apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-kubernetes
  namespace: tools
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    ---
    # sample kubernetes config