apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-proxmox
  namespace: tools
  labels:
    app.kubernetes.io/name: homepage
data:
  proxmox.yaml: |
    ---
    # url: https://proxmox.host.or.ip:8006
    # token: username@pam!Token ID
    # secret: secret