apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-services
  namespace: tools
  labels:
    app.kubernetes.io/name: homepage
data:
  services.yaml: |
    ---
    # For configuration options and examples, please see:
    # https://gethomepage.dev/configs/services/

    - Media:
        - Plex:
            icon: plex.png
            href: https://plex.conderhome.xyz
            ping: http://192.168.5.26:32400
            widget:
              type: plex
              url: http://192.168.5.26:32400
              key: "-bsJ6TySS3_6CZVRVzbr"
              fields: ["streams", "movies", "tv"] #optional
        - TrueNAS:
            icon: truenas
            href: https://nas.conderhome.xyz/
            description: Data Storage
            ping: https://192.168.5.18/
            widget:
              type: truenas
              url: https://192.168.5.18
              username: admin
              password: Baseball44
              enablePools: true
              nastype: scale
        - ReadMeABook:
            icon: readarr.png
            href: http://readmeabook.conderhome.xyz
        - Radarr:
            icon: radarr.png
            href: https://radarr.conderhome.xyz
            ping: https://radarr.conderhome.xyz
            widget:
              type: radarr
              url: https://radarr.conderhome.xyz
              key: 734410a0098a45b4bdfe80cc9c4bda09
              enableQueue: true # optional, defaults to false
        - Sonarr:
            icon: sonarr.png
            href: https://sonarr.conderhome.xyz
            ping: https://sonarr.conderhome.xyz
            widget:
              type: sonarr
              url: https://sonarr.conderhome.xyz
              key: 3db2b298f4754f2bbc1e25d7ab22d338
              enableQueue: true # optional, defaults to false
        - Prowlarr:
            icon: prowlarr.png
            href: https://prowlarr.conderhome.xyz
            ping: https://prowlarr.conderhome.xyz
            widget:
              type: prowlarr
              url: https://prowlarr.conderhome.xyz
              key: e094e354ccec4071b825889479aaa827
        - Qbit:
            icon: qbittorrent.png
            href: http://192.168.5.26:8080
            widget:
              type: qbittorrent
              url: http://192.168.5.26:8080
              username: admin
              password: Baseball44
              enableLeechProgress: true # optional, defaults to false
              enableLeechSize: true # optional, defaults to false
    - Network:
        # - UNIFI:
        #     icon: unifi.png
        #     href: http://192.168.5.1
        #     ping: 192.168.5.1
        #     widget:
        #       type: unifi
        #       url: https://192.168.5.1
        #       username: admin
        #       password: Baseball44
        #       # key: JbcZXUU-WrNj2XTUBF3mAqNJR2vaF6gl # required if using API key instead of username/password
        - MySpeed:
            icon: myspeed.png
            href: http://192.168.5.120:5216
            widget:
              type: myspeed
              url: http://192.168.5.120:5216
        - Pihole 1:
            icon: pi-hole.png
            href: http://192.168.5.5/admin
            ping: http://192.168.5.5/admin
            widget:
              version: 6
              type: pihole
              url: http://192.168.5.5
              key: Baseball44
              fields: ["queries", "blocked", "blocked_percent", "gravity"]
        - Pihole 2:
            icon: pi-hole.png
            href: http://192.168.5.6/admin
            ping: http://192.168.5.6/admin
            widget:
              version: 6
              type: pihole
              url: http://192.168.5.6
              key: Baseball44
              fields: ["queries", "blocked", "blocked_percent", "gravity"]
        - Wireless:
            icon: omada.png
            href: https://192.168.5.233:8043
            ping: https://192.168.5.233:8043
            widget:
              type: omada
              url: https://192.168.5.233:8043
              username: Root
              password: Baseball44!
              site: Omada.conderhome.xyz
        - Guest Network:
            icon: guest.png
            href: https://guest.conderhome.xyz
        - KeyShift:
            icon: keyshift.png
            href: https://guest.conderhome.xyz/admin
    - Services:
        - Termix:
            icon: termix.png
            href: https://termix.conderhome.xyz
        - NGINX Proxy Manager:
            icon: nginx-proxy-manager.png
            href: http://192.168.5.42:81
            ping: http://192.168.5.42:81
            widget:
              type: npm
              url: http://192.168.5.42:81
              username: m40a3lphoenix@gmail.com
              password: Baseball44
        - Wireguard:
            icon: wireguard.png
            href: http://192.168.5.42:5000
            ping: http://192.168.5.42:5000
            #widget:
              #type: wgeasy
              #url: http://192.168.5.16:5000
              #username: root
              #password: Baseball44
              #fields: ["connected", "enabled", "disabled", "total"]
        - Actual Budget:
            icon: actual-budget.png
            href: https://budget.conderhome.xyz
            ping: https://budget.conderhome.xyz
        - Vaultwarden:
            icon: vaultwarden.png
            href: https://vault.conderhome.xyz
            ping: vault.conderhome.xyz
        - Immich:
            icon: immich.png
            href: https://immich.conderhome.xyz
            ping: https://immich.conderhome.xyz
            widget:
              type: immich
              url: https://immich.conderhome.xyz
              key: tDgxMC9n4rN3aOO6KXFliVLKUgvKKzU6q4cx8TnU
              version: 2 # optional, default is 1
        - NexusTale:
            href: https://nexustale.conderhome.xyz
            ping: https://nexustale.conderhome.xyz
    - Infrastructure:
        - Authentik:
            icon: authentik.png
            href: https://auth.conderhome.xyz
            ping: https://auth.conderhome.xyz
            #widget:
              #type: authentik
              #url: https://auth.conderhome.xyz
              #key: JYy5O1pULGw40krp42Tw4BrPY6SRge7rQaCokG5om6V0sQiqU48psBIfIDKZ
        - Proxmox:
            icon: proxmox.png
            href: https://thunder.conderhome.xyz
            ping: https://192.168.5.10:8006
            widget:
              type: proxmox
              url: https://thunder.conderhome.xyz
              username: API@pam!homepage
              password: 41d176d1-bd7f-4c1f-aa79-32cf45936af7
              #node: pve-1 # optional
        - Dockhand:
            icon: dockhand.png
            href: https://dockhand.conderhome.xyz
            widget:
              type: dockhand
              url: https://dockhand.conderhome.xyz
              username: jconder44 # required for local auth
              password: Baseball44 # required for local auth
        - Grafana:
            icon: grafana.png
            href: http://dashboard.conderhome.xyz
            widget:
              type: grafana
              version: 2 # optional, default is 1
              alerts: grafana # optional, default is grafana
              url: http://192.168.5.48:3000
              username: jconder44
              password: Baseball44
        - HomeAssistant:
            icon: home-assistant.png
            href: http://192.168.5.19:8123
            widget:
              type: homeassistant
              url: http://192.168.5.19:8123
              key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmYzU2ODFiZWQwYTk0ZjkzYTA1YjdhNDk2MzM4ZmRhNCIsImlhdCI6MTc4NDIzMDQwNiwiZXhwIjoyMDk5NTkwNDA2fQ.f5pknSE1vRNeHoBA5jf--A5jf--Hlla6xTA3okVM6fTTktBVQ
              custom:
                - state: sensor.mts300_temperature
                - state: sensor.total_energy_today
                  label: energy today
                - template: "{{ states.switch|selectattr('state','equalto','on')|list|length }}"
                  label: switches on
                - state: weather.forecast_home
                  label: wind speed
                  value: "{attributes.wind_speed} {attributes.wind_speed_unit}"