apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-widgets
  namespace: tools
  labels:
    app.kubernetes.io/name: homepage
data:
  widgets.yaml: |
    ---
    # For configuration options and examples, please see:
    # https://gethomepage.dev/configs/info-widgets/

    - resources:
        cpu: true
        memory: true
        disk: /

    - search:
        provider: duckduckgo
        target: _blank

    - openmeteo:
        label: Home # optional
        latitude: 35.5965
        longitude: -88.6314
        timezone: America/Chicago # optional
        units: imperial # or imperial
        cache: 5 # Time in minutes to cache API responses, to stay within limits
        format: # optional, Intl.NumberFormat options
          maximumFractionDigits: 1