apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-conderhome-xyz
  namespace: cert-manager
spec:
  secretName: wildcard-conderhome-xyz-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.conderhome.xyz"
    - "conderhome.xyz"