apiVersion: ENC[AES256_GCM,data:K4A=,iv:BYZAHJkefYEiF01AyHk9thiwAqdtCjcCvGZlaYRydIQ=,tag:FndSR06yTgkHSZ3QV8Yjmw==,type:str]
kind: ENC[AES256_GCM,data:XYaWiRoo,iv:t0WJATv19AVpjI7CJGxv/oOwItEYo0jQvupW5crt2LE=,tag:IdS8UIY89CA6fKSZwWQeVQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kp6ZcYzG/NKk8nGg2Q==,iv:R1pz5lR+RMw7cjaw6v6FJFLEJHZm8BVPTzfsQUeHLR4=,tag:D0OxP6DOVd1XKn0OjbMNTg==,type:str]
    namespace: ENC[AES256_GCM,data:ueKar/U=,iv:0iTbUWR3By/doQoRnsoXFzy61NXL1S4eax5U265xs3o=,tag:fDvRRz2BYEIak9ZcgCR4Sw==,type:str]
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:miXLkTY8Fius14xd,iv:NxbT+NNsWY96wFF3gDT4eOCbXVfCK5eX7IszRISVXuk=,tag:tzZajgcaZ25TPnnNQTQKqg==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:nkJsERrvUUWU,iv:mZ/7aV/UbezF4RiD2nfKrSA65kRcVHuRlwx4UrHwnyA=,tag:LQJ/8HNdzHK8pa+cNkJBAg==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:Y8Zc6/XxjJ+bSg==,iv:7JUde89ni9nZvEiJv0j+VQzNskAZ6+LHRybD3LL2OHI=,tag:6UiUOL57C4SzxjTyHd1XFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dte6kqnx7ny2khum85yed0l50xgra99l3j7z0z79zs89jsxh6u4qzygfrf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsR1ZwcHVBWnJRemZ0dHpT
            Q2gzRUt5VVI5Y285UnluQnIySFJNNjhVK3lVCjNZelFUT1hGS1c2MlhJZnhlbWVG
            d3JvcjhIc2ZlUERENmxIME15Q280Q1UKLS0tIENnS0ErRFRSYU9YMENxMDhsS2pF
            VkQ0ZnUwdWRuV1A5Smh4aG1zTkN4YTAKZ3IG+cuCf+AB+ItU9ziB9xjEdjhB5GRM
            qiPNkF4qmu18QyQzOGXzhilU1S4hDAioXl3S5RA3urJDY0Vrzp/+Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T19:21:33Z"
    mac: ENC[AES256_GCM,data:/l/pyXoVWpfZWG13W2gSBaVH+aW3EKQwyg73BUbjcIbiL6JQrU1hDRNbcebea0wCqZUJ/3Dd+okSas+yZfiAEhROhQeEmy13K/F/514pEJqCzbUVWgLHC0RRQZzBleZefd9VIAD3OR8+ryCIYt1uG8N6m+Iv2+S3GiuqXUttgPI=,iv:YQa7waVDXQf1UTlOkl97kJlRvCGq1X6iObjMM/A1+cs=,tag:ecRXQJ+MsBpB5j/o/39UPg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
