apiVersion: ENC[AES256_GCM,data:E3A=,iv:3c4RbYNufKq8kmEjWXNjeaUYJFza+zoldDKYJuvCees=,tag:o+vumaDvdAPx3hzIlSq/fA==,type:str]
kind: ENC[AES256_GCM,data:1cXcGHqh,iv:uj4mMuDPjEXPE6pQv3+JWoLIiCNTnld+thhGxf/nMVo=,tag:ox1wBZNeGoNKkhmaLuFy2g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:805FidZRW1eS9ZNbu4SpD/UC,iv:hf8fGUitWAaCR+Oz9iMHVmoCKGitY2YFyegP0aOXpJs=,tag:1wKgo9dpAvEXaJSErdQ4hg==,type:str]
    namespace: ENC[AES256_GCM,data:CzEdXzdrwYVDfA==,iv:ur4wvj6g/pQb/GAcVwAH0VDVD6+kpgWigDT5Zesm+6I=,tag:4GnWTTBUgTMUTUdjK2hxKg==,type:str]
stringData:
    PROMETHEUS_ADMIN_USER: ENC[AES256_GCM,data:Hptn517jGhmd,iv:91L+l7jWP7jzbMO9+/0EMy1pSJo9ADntojhw9ynm9Mk=,tag:RUBZxWFFr4JKCc+lfP2caw==,type:str]
    PROMETHEUS_ADMIN_PASSWORD: ENC[AES256_GCM,data:ZwZGSC9zM76VjQ==,iv:1BDpbaTRlMOa81R5Kbl0F6ziYXIGz5nsWzYYQ5XUYE0=,tag:5pflxiPPeRbBd1eeX1xPhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dte6kqnx7ny2khum85yed0l50xgra99l3j7z0z79zs89jsxh6u4qzygfrf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsb2pwWW01aDdNTk4vQVBE
            MGFSdkFDYUdFc3hzY2ZJTnNXRlBGa29zMUhFCjl2blM0RnUxSEVvVFhvTEhCcnZk
            cjBieE9NRDkyVzJETmYwSWFLenNxTmsKLS0tIEtyeDJGNTQ2UWpERFc3TmhFVU9q
            K21YSCt3WitiS2pIVmFVMVU4ZjZBK3cKfXIGU4O7OYEi9MotEdABHISeEuWNLC7Q
            DapsPGqfMX84WP1QSNTyUj44j3dKQWL4yzPb6w9FkamD4zxAEWFzVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T19:22:21Z"
    mac: ENC[AES256_GCM,data:fWXznWndYSa82ywH6xrMD9SReRDi2OjLqzXaiTeQ3DW+d850OHWUbxY4l6TrDZE+QrOTox1O5s0VeF8U08iMNEVMtqcyT6XRHdTXXzefK63gjLekJ5avvvpArCZ8+fyjuXMN8NWPd1/BGzpxnuKpjasDhsJk9X4m+Q8dpGS+SNA=,iv:58KUSK6UCMxzqvZFFZx4bgRVdvwQm37gVFeyswjzNUc=,tag:LRnw6IUARkyYMVRdspvA1g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
