apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yml
  - secrets.yml
generatorOptions:
  labels:
    grafana_dashboard: "1"
configMapGenerator:
  - name: homelab-overview-dashboard
    namespace: monitoring
    files:
      - homelab-overview.json=dashboards/homelab-overview.json
