apiVersion: ENC[AES256_GCM,data:uCs=,iv:aqYFyGv5eaZ91QGxL6zrtSlR+tk02v4un98xkfaUrSE=,tag:2D09ccqWUn8CNEsX63Ql+Q==,type:str]
kind: ENC[AES256_GCM,data:PPaC1dGH,iv:j4X4+gk+WxECUU+NUt6fYpyJpGrM/ea/h8Xaw2JHtOU=,tag:y2p3n0a4TCSwXCUI4/qcLg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LD6H80RB4k9hFTn0Mkp0,iv:KUTxfkVXT+Sej4c9zfWLTJVV94LMqi5PXKES4UI3lKk=,tag:bQ3qY6djdSx92wsdMK0fhw==,type:str]
    namespace: ENC[AES256_GCM,data:IGOvUK4f6Se/VQ==,iv:7tUsmd0t4IaWl3VHE8cMb2fXKH7OiUAg+hKMakUpXUU=,tag:jU45FMkKSPEG6wGDu8adXg==,type:str]
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:GMCSCprve0L1,iv:KNpbpiiW8P1i29D+YYZaltaWzyxN+ld3R/bG5CGF1FE=,tag:EUddGzgKi7hZ5wjS+l9mLQ==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:Jo5yCehtaxjjrA==,iv:cP1nqVWrvb4htTcan//mPOoyWpinl9XhZ760GEoV6OI=,tag:iMYeiF93Kj52rYSAWW/iYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dte6kqnx7ny2khum85yed0l50xgra99l3j7z0z79zs89jsxh6u4qzygfrf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdVRFajFyK2twWWV1UHJN
            aVVsMHlQL2xiUzdjZ3pFaXMyMWJFRExWblNnClR6WllZUHJVZVBTNlU3ektxZ1NL
            aTkzMFpweVlLNDNRM0hOR0NYMGJSd1kKLS0tIFRVLzBXS1VON3J1aEFxU1JDeDBo
            NG1BYkZvVHdQN09SblZndmZOdm9Fa0kKHq0W6azF4PZNpHt9jeUY/Z9MLW4rgSKW
            7ufPAd/a2Koa6KgkhzNGois07MWZgsVS1+kkHAowA0RhOxQbKyjVnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T19:22:21Z"
    mac: ENC[AES256_GCM,data:C42M0rkJIzPUtPGAjzcl9I7iOJTBtnfStlZL2y883t8Wx+58RtEU2TM8iP6oTmH38fEIVQdeOIhLzrhyHOYb//SZHG5UYttWG1U3vEq6EacsS5ofzlOrTSkAwdyDUAf7un/DdPsusTCKppqrkD2iYCLxBEedyBPygJcSuI3W3UE=,iv:Y5Qa22c2r2u7Opx8pj4Qwzzx9c6GFBhEzJyCYOMOglc=,tag:D5oSLJiLIyLxPj1HqfoMUg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
