apiVersion: ENC[AES256_GCM,data:Y20=,iv:bxL9tiP+oEDa7l15rTDxyIs6JvXSc+3o5NWnX3Fhz9o=,tag:mw5+ID8gkh/e8P9X/rrvMw==,type:str]
kind: ENC[AES256_GCM,data:yAtWi6LF,iv:vzr1kswW5Vr0AtIXD/smvS3RuQ4EZnJdCDHsGmODvqk=,tag:1OC+f54kl6XIoFS/oJ9pkQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IiUK+hXQkP2rj2ulgv9K+tdJeg==,iv:H4tFNsMlyvo2mzGywdzopc8ycHfeDm3Y4q3NGf8emlE=,tag:Ic3sEKB+tA51E1UkaYjxBQ==,type:str]
    namespace: ENC[AES256_GCM,data:V54CbZM=,iv:OVOvR+Vwcl33tyEb15XcVKvu+pYVwVitraUMSQ36geY=,tag:Ux5Djvl+w50wSk4zoJyHpA==,type:str]
stringData:
    address: ENC[AES256_GCM,data:OnEA6KFXSqrpqKf0uP3cFiFD,iv:PQ+6TtxpcJw+4w7kUqyvYB085vg2XbIfK84rxLmqnnc=,tag:knUiCeAnI8xnh4wH/67zFg==,type:str]
    password: ENC[AES256_GCM,data:rPbA1d1pCdp+aQ==,iv:uhRoAuXWb2WvqQrREdLCEYLGvhsG5bcrxgBldyC6ouQ=,tag:7uAFIcv/O4AIOZoOdqdR9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dte6kqnx7ny2khum85yed0l50xgra99l3j7z0z79zs89jsxh6u4qzygfrf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SVNyUmhqMHE4b0UwLzdz
            ckorME11bzFzSXVPZkxvN1EvVEQxWHJrWjFBCjU5RFJ6NFg5Zm8xSmx6TiswRnIr
            UWJ2aGtSU044cWx6SkhmcWI4aC9NbDQKLS0tIGM1WVZqaloyRnRMN3dONVJ0QUds
            NEVjRCtCZ3N3TzY2d2xUUnZ0UU9qMGMKqGaXagIeWkp06H3eutOY24FixsFdtv/X
            H/eF57czq3mhK5aEpkgcJN6PBeRZFaSNpsDo/oGDQ81RytIbfFut6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T15:25:09Z"
    mac: ENC[AES256_GCM,data:4eETDOVKsEiHRbvzi3p9GSx3B0qcpbePqODS/UASPQJls2emWyxbLCpsLAX5/yy2Xp7h/DJwp2UhHcAo1lXqlUQfVTf4Ksbzr+ZLEZdO/uqQnX5tppVxNf+VVDSUIO9UakTjvgyzTrF0+QSZlZ5x7U1YqbwewvcUb/+FhKOAlkY=,iv:urwB/07AUg194R859ULrsqX6BPrytVrtVI4ON7m4X5s=,tag:k8isegI1GeTUSsYJeXpV7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
